//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodeLive.MVVM.Model
{
    using System;
    using System.Collections.Generic;

    public partial class ChiTietHoaDon
    {
        public int SoHoaDon { get; set; }
        public string MaMonAn { get; set; }
        public Nullable<int> SoLuong { get; set; }

        public virtual MonAn MonAn { get; set; }
        public virtual HoaDon HoaDon { get; set; }

        public ChiTietHoaDon()
        {
            this.MonAn = new MonAn();
            this.HoaDon = new HoaDon();
        }

        public ChiTietHoaDon(int SoHoaDon, string MaMonAn, Nullable<int> SoLuong, MonAn monAn, HoaDon hoaDon)
        {
            this.MonAn = new MonAn();
            this.HoaDon = new HoaDon();
            this.SoHoaDon = SoHoaDon;
            this.MaMonAn = MaMonAn;
            this.SoLuong = SoLuong;
            this.MonAn = monAn;
            this.HoaDon = hoaDon;
        }
    }
}
